version: 2.1

jobs:
  say-hello:
   docker:
      - image: cimg/base:current
      
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
workflows:
  say-hello-workflow: 
    jobs:
      - say-hello

- run:
    name: Plan a deploy
    command: |
      circleci run release plan \
        --environment-name="<environment-name>" \
        --component-name="<component-name>" \
        --target-version="<some-version-name>"
# Your job here doing the actual deployment
- run:
    name: Update a deploy to SUCCESS
    command: circleci run release update --status=SUCCESS 
    when: on_success 
- run:
    name: Update planned deploy to FAILED
    command: circleci run release update --status=FAILED 
    when: on_fail
