version: 2.1

job:
  build-and-test:
    # Using a specific version of the Rust image for reproducible builds
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - run:
          name: "Check formatting"
          command: "cargo fmt -- --check"
      - run:
          name: "Lint with Clippy"
          command: "cargo clippy --all-targets -- -D warnings"
      - run:
          name: "Run tests"
          command: "cargo test"
