  build_and_test:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - run:
          name: "Check formatting"
          command: "cargo fmt --all -- --check"
      - run:
          name: "Run Clippy"
          command: "cargo clippy --all-targets -- -D warnings"
      - run:
          name: "Run tests"
          command: "cargo test --all-features"
