version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/rust:1.78.0
    steps:
      - checkout
      - run:
          name: "Check formatting"
          command: cargo fmt -- --check
      - run:
          name: "Run tests"
          command: cargo test

workflows:
  ci:
    jobs:
      - build-and-test
