# This is a starter workflow to help you get started with APIsec-Scan Actions
name: APIsec

on: [push, pull_request]

jobs:
  Trigger_APIsec_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run APIsec scan
      uses: apisec-inc/apisec-run-scan@025432089674a28ba8fb55f8ab06c10215e772ea
      with:
        apisec-project: VAmPI
        sarif-result-file: apisec-results.sarif
        apisec-profile: Master
        apisec-oas: false
        # Ensure you provide valid credentials and host details
        username: ${{ secrets.APISEC_USERNAME }}
        password: ${{ secrets.APISEC_PASSWORD }}
        host: ${{ secrets.APISEC_HOST }}
        scanner: "default-scanner"
