name: APIsec
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run APIsec scan
      uses: apisec-inc/apisec-run-scan@025432089674a28ba8fb55f8ab06c10215e772ea
      with:
        apisec-username: ${{ secrets.APISEC_USERNAME }}
        apisec-password: ${{ secrets.APISEC_PASSWORD }}
        apisec-project: VAmPI
        apisec-profile: Master
        apisec-region: us-east-1
        sarif-result-file: apisec-results.sarif
        apisec-email-report: true
        apisec-fail-on-vuln-severity: critical
        apisec-oas: false
        apisec-openapi-spec-url: "https://example.com/openapi.json"
